package com.silisurfers.savnac.database.entities;

import static androidx.room.ForeignKey.CASCADE;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/***
 * Author: Wootark (Tom) Kim
 * Date creation: 14 April 2024
 * Purpose of file: a JAVA class acting as an Entity file for Enrollment.
 */

    // Important note (SavnacEnrollment vs SavnacCourse):
    // "SavnacEnrollment" is a table for a list of courses enrolled by the user
    // "SavnacCourse" is a table for a list of available courses that the user can enroll in

@Entity(
        tableName = "enrollments", //by vw
        foreignKeys = {
            @ForeignKey(
                entity = SavnacUser.class,
                parentColumns = "id",
                childColumns = "student_id",
                onDelete = CASCADE
            ),
            @ForeignKey(
                entity = SavnacCourse.class,
                parentColumns = "id",
                childColumns = "course_id",
                onDelete = CASCADE
            )
        },
        indices = {
            @Index("student_id"),
            @Index("course_id")
        }
)    // Setting a custom name for the data table
public class SavnacEnrollment {

    @PrimaryKey(autoGenerate = true)        // Autogenerate set to true so we do not have to manually
    private int id;                         // provide an id for each row. Room will take care of it.

    @ColumnInfo(name = "course_id")     // Creating a column called "courseName."
    private int courseId;

    @ColumnInfo(name = "student_id")
    private int studentId;

    // [Constructor]================================================================================
    /**
     * Each instantiation of the "SavnacEnrollment" object by using the constructor represents one
     * row of the enrollmentOptions table (in this case, one row per className)
     */
    public SavnacEnrollment(int studentId, int courseId){
        this.studentId = studentId;
        this.courseId = courseId;
    }

    // [Autogenerated Getters and Setters]==========================================================
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getCourseId() {
        return courseId;
    }

    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }

    public int getStudentId() {
        return studentId;
    }

    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
}