package com.silisurfers.savnac.database.entities;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/***
 * Author: Wootark (Tom) Kim
 * Date creation: 14 April 2024
 * Purpose of file: a JAVA class acting as an Entity file for Enrollment.
 */

    // Important note (SavnacEnrollment vs SavnacCourse):
    // "SavnacEnrollment" is a table for a list of courses enrolled by the user
    // "SavnacCourse" is a table for a list of available courses that the user can enroll in

@Entity(tableName = "enrollmentOptions")    // Setting a custom name for the data table
public class SavnacEnrollment {

    @PrimaryKey(autoGenerate = true)        // Autogenerate set to true so we do not have to manually
    private int id;                         // provide an id for each row. Room will take care of it.

    @ColumnInfo(name = "class_options")     // Creating a column called "class_options."
    private String courseName;

    // [Constructor]================================================================================
    /**
     * Each instantiation of the "SavnacEnrollment" object by using the constructor represents one
     * row of the enrollmentOptions table (in this case, one row per className)
     */
    public SavnacEnrollment(String courseName){
        this.courseName = courseName;
    }

    // [Autogenerated Getters and Setters]==========================================================
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
}