package com.silisurfers.savnac.database.entities;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/***
 * Author: Wootark Kim
 * Date creation: 14 April 2024
 * Purpose of file: a JAVA class acting as an Entity file for Enrollment.
 */

@Entity(tableName = "enrollmentOptions")    // Setting a custom name for the data table
public class SavnacEnrollment {

    @PrimaryKey(autoGenerate = true)        // Autogenerate set to true so we do not have to manually
    private int id;                         // provide an id for each row. Room will take care of it.

    @ColumnInfo(name = "class_options")     // Creating a column called "className."
    private String className;

    // [Constructor]================================================================================
    /**
     * Each instantiation of the "SavnacEnrollment" object by using the constructor represents one
     * row of the enrollmentOptions table (in this case, one row per className)
     */
    public SavnacEnrollment(String className){
        this.className = className;
    }

    // [Autogenerated Getters and Setters]==========================================================
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }
}